
package organigrammClient.OrganigrammServer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OrganigrammServerService", targetNamespace = "http://organigrammServer/", wsdlLocation = "http://localhost:9090/OrganigrammServices?wsdl")
public class OrganigrammServerService
    extends Service
{

    private final static URL ORGANIGRAMMSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException ORGANIGRAMMSERVERSERVICE_EXCEPTION;
    private final static QName ORGANIGRAMMSERVERSERVICE_QNAME = new QName("http://organigrammServer/", "OrganigrammServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/OrganigrammServices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ORGANIGRAMMSERVERSERVICE_WSDL_LOCATION = url;
        ORGANIGRAMMSERVERSERVICE_EXCEPTION = e;
    }

    public OrganigrammServerService() {
        super(__getWsdlLocation(), ORGANIGRAMMSERVERSERVICE_QNAME);
    }

    public OrganigrammServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ORGANIGRAMMSERVERSERVICE_QNAME, features);
    }

    public OrganigrammServerService(URL wsdlLocation) {
        super(wsdlLocation, ORGANIGRAMMSERVERSERVICE_QNAME);
    }

    public OrganigrammServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ORGANIGRAMMSERVERSERVICE_QNAME, features);
    }

    public OrganigrammServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrganigrammServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OrganigrammServer
     */
    @WebEndpoint(name = "OrganigrammServerPort")
    public OrganigrammServer getOrganigrammServerPort() {
        return super.getPort(new QName("http://organigrammServer/", "OrganigrammServerPort"), OrganigrammServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrganigrammServer
     */
    @WebEndpoint(name = "OrganigrammServerPort")
    public OrganigrammServer getOrganigrammServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://organigrammServer/", "OrganigrammServerPort"), OrganigrammServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ORGANIGRAMMSERVERSERVICE_EXCEPTION!= null) {
            throw ORGANIGRAMMSERVERSERVICE_EXCEPTION;
        }
        return ORGANIGRAMMSERVERSERVICE_WSDL_LOCATION;
    }

}
