
package organigrammClient.OrganigrammServer;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrganigrammServer", targetNamespace = "http://organigrammServer/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrganigrammServer {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateAbteilung", targetNamespace = "http://organigrammServer/", className = "organigrammClient.OrganigrammServer.UpdateAbteilung")
    @ResponseWrapper(localName = "updateAbteilungResponse", targetNamespace = "http://organigrammServer/", className = "organigrammClient.OrganigrammServer.UpdateAbteilungResponse")
    @Action(input = "http://organigrammServer/OrganigrammServer/updateAbteilungRequest", output = "http://organigrammServer/OrganigrammServer/updateAbteilungResponse")
    public boolean updateAbteilung(
        @WebParam(name = "arg0", targetNamespace = "")
        Abteilung arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteAbteilung", targetNamespace = "http://organigrammServer/", className = "organigrammClient.OrganigrammServer.DeleteAbteilung")
    @ResponseWrapper(localName = "deleteAbteilungResponse", targetNamespace = "http://organigrammServer/", className = "organigrammClient.OrganigrammServer.DeleteAbteilungResponse")
    @Action(input = "http://organigrammServer/OrganigrammServer/deleteAbteilungRequest", output = "http://organigrammServer/OrganigrammServer/deleteAbteilungResponse")
    public boolean deleteAbteilung(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns organigrammClient.OrganigrammServer.Abteilung
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addAbteilung", targetNamespace = "http://organigrammServer/", className = "organigrammClient.OrganigrammServer.AddAbteilung")
    @ResponseWrapper(localName = "addAbteilungResponse", targetNamespace = "http://organigrammServer/", className = "organigrammClient.OrganigrammServer.AddAbteilungResponse")
    @Action(input = "http://organigrammServer/OrganigrammServer/addAbteilungRequest", output = "http://organigrammServer/OrganigrammServer/addAbteilungResponse")
    public Abteilung addAbteilung(
        @WebParam(name = "arg0", targetNamespace = "")
        Abteilung arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns organigrammClient.OrganigrammServer.Mitarbeiter
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addMitarbeiter", targetNamespace = "http://organigrammServer/", className = "organigrammClient.OrganigrammServer.AddMitarbeiter")
    @ResponseWrapper(localName = "addMitarbeiterResponse", targetNamespace = "http://organigrammServer/", className = "organigrammClient.OrganigrammServer.AddMitarbeiterResponse")
    @Action(input = "http://organigrammServer/OrganigrammServer/addMitarbeiterRequest", output = "http://organigrammServer/OrganigrammServer/addMitarbeiterResponse")
    public Mitarbeiter addMitarbeiter(
        @WebParam(name = "arg0", targetNamespace = "")
        Mitarbeiter arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Integer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMitarbeiterIdListe", targetNamespace = "http://organigrammServer/", className = "organigrammClient.OrganigrammServer.GetMitarbeiterIdListe")
    @ResponseWrapper(localName = "getMitarbeiterIdListeResponse", targetNamespace = "http://organigrammServer/", className = "organigrammClient.OrganigrammServer.GetMitarbeiterIdListeResponse")
    @Action(input = "http://organigrammServer/OrganigrammServer/getMitarbeiterIdListeRequest", output = "http://organigrammServer/OrganigrammServer/getMitarbeiterIdListeResponse")
    public List<Integer> getMitarbeiterIdListe(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<organigrammClient.OrganigrammServer.Abteilung>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAbteilungsListe", targetNamespace = "http://organigrammServer/", className = "organigrammClient.OrganigrammServer.GetAbteilungsListe")
    @ResponseWrapper(localName = "getAbteilungsListeResponse", targetNamespace = "http://organigrammServer/", className = "organigrammClient.OrganigrammServer.GetAbteilungsListeResponse")
    @Action(input = "http://organigrammServer/OrganigrammServer/getAbteilungsListeRequest", output = "http://organigrammServer/OrganigrammServer/getAbteilungsListeResponse")
    public List<Abteilung> getAbteilungsListe(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteMitarbeiter", targetNamespace = "http://organigrammServer/", className = "organigrammClient.OrganigrammServer.DeleteMitarbeiter")
    @ResponseWrapper(localName = "deleteMitarbeiterResponse", targetNamespace = "http://organigrammServer/", className = "organigrammClient.OrganigrammServer.DeleteMitarbeiterResponse")
    @Action(input = "http://organigrammServer/OrganigrammServer/deleteMitarbeiterRequest", output = "http://organigrammServer/OrganigrammServer/deleteMitarbeiterResponse")
    public boolean deleteMitarbeiter(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateMitarbeiter", targetNamespace = "http://organigrammServer/", className = "organigrammClient.OrganigrammServer.UpdateMitarbeiter")
    @ResponseWrapper(localName = "updateMitarbeiterResponse", targetNamespace = "http://organigrammServer/", className = "organigrammClient.OrganigrammServer.UpdateMitarbeiterResponse")
    @Action(input = "http://organigrammServer/OrganigrammServer/updateMitarbeiterRequest", output = "http://organigrammServer/OrganigrammServer/updateMitarbeiterResponse")
    public boolean updateMitarbeiter(
        @WebParam(name = "arg0", targetNamespace = "")
        Mitarbeiter arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns organigrammClient.OrganigrammServer.Mitarbeiter
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMitarbeiterDetails", targetNamespace = "http://organigrammServer/", className = "organigrammClient.OrganigrammServer.GetMitarbeiterDetails")
    @ResponseWrapper(localName = "getMitarbeiterDetailsResponse", targetNamespace = "http://organigrammServer/", className = "organigrammClient.OrganigrammServer.GetMitarbeiterDetailsResponse")
    @Action(input = "http://organigrammServer/OrganigrammServer/getMitarbeiterDetailsRequest", output = "http://organigrammServer/OrganigrammServer/getMitarbeiterDetailsResponse")
    public Mitarbeiter getMitarbeiterDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
